## -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
    obj = bld.create_ns3_program('gcc_tcp',
                                 ['core','razor-ns3','internet','network','point-to-point', 'applications','traffic-control'])
    obj.source = 'gcc_tcp.cc'
